export const muscles = [
  "Abductor Brevis",
  "Adductor Brevis",
  "Adductor Longus",
  "Adductor Magnus",
  "Anterior Deltoid",
  "Biceps Brachii",
  "Brachialis",
  "Brachioradialis",
  "Clavicular Head",
  "Erector Spinae",
  "Gastrocnemius",
  "Gluteus Maximus",
  "Gluteus Medius",
  "Gracilis",
  "Hamstring",
  "Hip Flexor",
  "Iliopsoas",
  "Infraspinatus",
  "Lateral Deltoid",
  "Latissimus Dorsi",
  "Levator Scapulae",
  "Obliques",
  "Pectineous",
  "Pectoralis Major Clavicular Head",
  "Pectoralis Major Sternal Head",
  "Popliteus",
  "Posterior Deltoid",
  "Quadriceps",
  "Rectus Abdominis",
  "Sartorius",
  "Serratus Anterior",
  "Soleus",
  "Splenius",
  "Sternocleidomastoid",
  "Tensor Fasciae Latae",
  "Teres Major",
  "Teres Minor",
  "Tibialis Anterior",
  "Trapezius Lower Fibers",
  "Trapezius Middle Fibers",
  "Trapezius Upper Fibers",
  "Triceps Brachii",
  "Wrist Extensors",
  "Wrist Flexors",
];

export const muscleAreas = [
  "Abdominals",
  "Abductors",
  "Adductors",
  "Arms",
  "Back",
  "Biceps",
  "Calves",
  "Cardio",
  "Cardio-Functional",
  "Chest",
  "Forearms",
  "Full Body",
  "Glutes",
  "Hamstrings",
  "Hip Flexors",
  "Legs",
  "Neck",
  "Quads",
  "Shoulders",
  "Stretching",
  "Triceps",
];
